###
GET https://api.upstox.com/v2/expired-instruments/option/contract
Accept: application/json
Content-Type: application/json
Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0R0NVTjQiLCJqdGkiOiI2OTM3OTQ0NjQ1MjY4MzczOTgyZWQyNTciLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzY1MjUwMTE4LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NjUzMTc2MDB9.U3SiD2JtAR0N52KxMx7tE2zGqW-faFomkj3atMzKJpI'

{
    "instrument_key": "NSE_INDEX|Nifty 50",
    "expiry_date": "2024-01-04"
}
###
